name: sipasti
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2 

  google_fonts: ^5.1.0

  cupertino_icons: ^1.0.8

  file_picker: ^4.0.0

  image_picker: ^0.8.4+3 

  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^4.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/jtilogo.png"

flutter:
  uses-material-design: true
  assets:
  - assets/logo_JTIpolinema.png
  - assets/jtilogo.png
  - assets/Rekomendasi.png
  - assets/pelatihan_1.png
  - assets/pelatihan_2.jpg
  - assets/Sertifikasi_1.jpg
  - assets/Sertifikasi_2.png
  - assets/profile.jpg

  